#use: mkmf -t Makefile.template -p nbo.exe
#to generate a proper makefile

MKLROOT=/opt/intel/compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64/


LD=ifort
FC=ifort
FFLAGS= -I$(MKLROOT) -qopenmp 
LDFLAGS=-L$(MKLROOT) -qopenmp -lmkl_blas95_lp64 -lmkl_lapack95_lp64 -lpthread -lm -I$(MKLROOT) -mkl=sequential
